# Generated by Django 3.2.4 on 2021-07-28 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatID', models.CharField(max_length=50, unique=True)),
                ('chatName', models.CharField(default='', max_length=50)),
                ('isDirectMessage', models.BooleanField(default=False)),
                ('lastChatTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('timeCreated', models.DateTimeField()),
                ('downloadURL', models.TextField()),
                ('isPrivate', models.BooleanField(default=False)),
                ('isImage', models.BooleanField()),
                ('isFlagged', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.FloatField(default=0.1)),
                ('nature', models.FloatField(default=0.1)),
                ('travel', models.FloatField(default=0.1)),
                ('music', models.FloatField(default=0.1)),
                ('fitness', models.FloatField(default=0.1)),
                ('art', models.FloatField(default=0.1)),
                ('dance', models.FloatField(default=0.1)),
                ('comedy', models.FloatField(default=0.1)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exists', models.BooleanField(default=False)),
                ('isImage', models.BooleanField(default=True)),
                ('downloadURL', models.TextField(default='')),
                ('isFlagged', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(default='', max_length=15)),
                ('uid', models.CharField(max_length=50, unique=True)),
                ('deviceToken', models.TextField(blank=True, default=None, null=True)),
                ('isUpdated', models.BooleanField(default=True)),
                ('username', models.CharField(default='', max_length=20)),
                ('preferredLanguage', models.CharField(default='', max_length=20)),
                ('profileColor', models.CharField(default='1', max_length=10)),
                ('signedIn', models.BooleanField(default=False)),
                ('preferences', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.preferences')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.profile')),
            ],
        ),
        migrations.CreateModel(
            name='WatchedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.user')),
            ],
        ),
        migrations.CreateModel(
            name='Reported',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.user')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created', to='models.user'),
        ),
        migrations.AddField(
            model_name='post',
            name='preferences',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.preferences'),
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newFollower', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='models.user')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followings', to='models.user')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isOwner', models.BooleanField(default=False)),
                ('isUpdated', models.BooleanField(default=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_members', to='models.chat')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.user')),
            ],
        ),
        migrations.CreateModel(
            name='Blocked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='models.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_blocking', to='models.user')),
            ],
        ),
    ]
