# Generated by Django 3.1.5 on 2021-05-28 20:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timeCreated',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 20, 40, 3, 107230, tzinfo=utc)),
        ),
    ]
