# Generated by Django 3.2.4 on 2021-07-28 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isUpdated',
        ),
    ]
