# Generated by Django 3.1.5 on 2021-05-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signedIn',
            field=models.BooleanField(default=False),
        ),
    ]
