# Generated by Django 3.1.5 on 2021-05-26 13:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20210526_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='demographics',
            new_name='preferences',
        ),
        migrations.AlterField(
            model_name='post',
            name='timeCreated',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 13, 25, 27, 448328, tzinfo=utc)),
        ),
    ]
