# Generated by Django 3.1.5 on 2021-06-01 14:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20210528_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='isDirectMessage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='timeCreated',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 14, 1, 11, 62382, tzinfo=utc)),
        ),
    ]
