# Generated by Django 3.1.5 on 2021-06-01 15:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20210601_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmember',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_members', to='models.chat'),
        ),
        migrations.AlterField(
            model_name='post',
            name='timeCreated',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 15, 4, 28, 173105, tzinfo=utc)),
        ),
    ]
