# Generated by Django 3.1.5 on 2021-06-01 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20210601_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postID',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='timeCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
