# Generated by Django 3.1.5 on 2021-06-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_auto_20210601_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileColor',
            field=models.CharField(default='blue', max_length=10),
        ),
    ]
