# Generated by Django 3.1.5 on 2021-06-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_user_profilecolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='female',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='male',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='other',
        ),
        migrations.AddField(
            model_name='preferences',
            name='fitness',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='preferences',
            name='food',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='preferences',
            name='music',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='preferences',
            name='nature',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='preferences',
            name='travel',
            field=models.FloatField(default=0.1),
        ),
    ]
