# Generated by Django 3.1.5 on 2021-06-09 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_auto_20210609_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='y0_12',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='y13_18',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='y19_24',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='y25_29',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='y30_34',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='y35_39',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='y40_49',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='y50_59',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='y60_up',
        ),
    ]
