# Generated by Django 3.2.4 on 2021-06-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_auto_20210609_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='outdoors',
            field=models.FloatField(default=0.1),
        ),
    ]
