# Generated by Django 3.2.4 on 2021-06-16 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_preferences_coding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='coding',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='gaming',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='lifestyle',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='outdoors',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='selfHelp',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='skits',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='sports',
        ),
    ]
