# Generated by Django 3.2.4 on 2021-06-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timeCreated',
            field=models.CharField(default='<function now at 0x7fe0c0af54c0>', max_length=100),
        ),
    ]
