# Generated by Django 3.2.4 on 2021-06-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0015_alter_post_timecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='timeCreated',
            field=models.CharField(default='<function now at 0x7fb7d8a754c0>', max_length=100),
        ),
    ]
