# Generated by Django 3.2.4 on 2021-06-17 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0016_auto_20210617_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='downloadURL',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='timeCreated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='downloadURL',
            field=models.CharField(default='', max_length=150),
        ),
    ]
