# Generated by Django 3.2.4 on 2021-06-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0018_auto_20210617_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='numReports',
            field=models.IntegerField(default=0),
        ),
    ]
