# Generated by Django 3.2.4 on 2021-06-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0019_post_numreports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationships',
            name='relation',
            field=models.IntegerField(choices=[(0, 'Following')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='profileColor',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
