# Generated by Django 3.2.4 on 2021-06-20 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0020_auto_20210620_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='allRelationships',
        ),
        migrations.CreateModel(
            name='Blocked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_blocking', to='models.user')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_blocked', to='models.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='blocked',
            field=models.ManyToManyField(through='models.Blocked', to='models.User'),
        ),
    ]
