# Generated by Django 3.2.4 on 2021-06-20 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0022_auto_20210620_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='models.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_blocking', to='models.user')),
            ],
        ),
    ]
