# Generated by Django 3.2.4 on 2021-07-05 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0025_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferredLanguage',
        ),
    ]
