# Generated by Django 3.2.4 on 2021-07-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0026_remove_user_preferredlanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferredLanguage',
            field=models.CharField(default='', max_length=20),
        ),
    ]
