# Generated by Django 3.2.4 on 2021-07-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0027_user_preferredlanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timeCreated',
            field=models.DateTimeField(),
        ),
    ]
