# Generated by Django 3.2.4 on 2021-07-12 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0028_alter_post_timecreated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='watchedBy',
        ),
        migrations.CreateModel(
            name='WatchedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.user')),
            ],
        ),
    ]
