# Generated by Django 3.2.4 on 2021-07-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0030_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileColor',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
