# Generated by Django 3.2.4 on 2021-07-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0030_reported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='numReports',
        ),
        migrations.AddField(
            model_name='chat',
            name='lastChatTime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chatmember',
            name='isUpdated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='isFlagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='isFlagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='deviceToken',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profileColor',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
