# Generated by Django 3.2.4 on 2021-07-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0031_auto_20210729_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isUpdated',
            field=models.BooleanField(default=True),
        ),
    ]
