# Generated by Django 3.2.4 on 2021-07-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0031_alter_user_profilecolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deviceToken',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
