# Generated by Django 3.2.4 on 2021-07-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0032_auto_20210729_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='lastChatTime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
