# Generated by Django 3.2.4 on 2021-07-23 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0032_alter_user_devicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='lastChatTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
