# Generated by Django 3.2.4 on 2021-07-23 14:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0033_chat_lastchattime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='lastChatTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 23, 14, 12, 48, 598833, tzinfo=utc)),
        ),
    ]
