# Generated by Django 3.2.4 on 2021-08-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0033_post_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isAppUpdated',
            field=models.BooleanField(default=True),
        ),
    ]
