# Generated by Django 3.2.4 on 2022-02-21 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0036_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedby',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched', to='models.post'),
        ),
        migrations.AlterField(
            model_name='watchedby',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_by', to='models.user'),
        ),
    ]
