# Generated by Django 3.2.4 on 2022-02-21 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0038_auto_20220221_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reported',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_by', to='models.post'),
        ),
        migrations.AlterField(
            model_name='reported',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported', to='models.user'),
        ),
    ]
