# Generated by Django 3.1.5 on 2021-01-31 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demographics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('preferredLanguage', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Relationships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.IntegerField(choices=[(0, 'Following'), (1, 'Blocked')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=50)),
                ('username', models.CharField(default='', max_length=20)),
                ('accountInfo', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_profile.accountinfo')),
                ('allFriends', models.ManyToManyField(related_name='_userprofile_allFriends_+', to='user_profile.UserProfile')),
                ('allRelationships', models.ManyToManyField(through='user_profile.Relationships', to='user_profile.UserProfile')),
                ('demographics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demographics.demographics')),
            ],
        ),
        migrations.AddField(
            model_name='relationships',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='user_profile.userprofile'),
        ),
        migrations.AddField(
            model_name='relationships',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followings', to='user_profile.userprofile'),
        ),
    ]
