# Generated by Django 3.1.5 on 2021-04-02 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_accountinfo_profilepicstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountinfo',
            old_name='profilePicStatus',
            new_name='profileType',
        ),
    ]
