# Generated by Django 3.1.4 on 2020-12-19 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0002_auto_20201219_1457'),
        ('user_profile', '0002_auto_20201219_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='accountInfo',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_profile.accountinfo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='demographics',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demographics.demographics'),
        ),
    ]
