# Generated by Django 3.1.5 on 2021-04-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20210402_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='profileType',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
