# Generated by Django 3.1.5 on 2021-05-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20210416_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationships',
            name='newFollower',
            field=models.BooleanField(default=True),
        ),
    ]
