# Generated by Django 3.1.4 on 2020-12-17 21:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostProfile',
            fields=[
                ('postID', models.AutoField(primary_key=True, serialize=False)),
                ('private', models.BooleanField(default=False)),
                ('timeCreated', models.DateTimeField(default=datetime.datetime.now)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created', to='user_profile.userprofile')),
            ],
        ),
    ]
