# Generated by Django 3.1.5 on 2021-01-31 16:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
        ('demographics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostProfile',
            fields=[
                ('postID', models.AutoField(primary_key=True, serialize=False)),
                ('private', models.BooleanField(default=False)),
                ('timeCreated', models.DateTimeField(default=datetime.datetime.now)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created', to='user_profile.userprofile')),
                ('demographics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demographics.demographics')),
                ('watchedBy', models.ManyToManyField(related_name='watched_by', to='user_profile.UserProfile')),
            ],
        ),
    ]
