# Generated by Django 3.1.4 on 2020-12-19 15:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
        ('demographics', '0002_auto_20201219_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostProfile',
            fields=[
                ('postID', models.AutoField(primary_key=True, serialize=False)),
                ('private', models.BooleanField(default=False)),
                ('timeCreated', models.DateTimeField(default=datetime.datetime.now)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created', to='user_profile.userprofile')),
                ('demographics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demographics.demographics')),
            ],
        ),
    ]
