# Generated by Django 3.1.4 on 2020-12-19 16:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20201219_1637'),
        ('post_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeWatched', models.DateTimeField(default=datetime.datetime.now)),
                ('userRating', models.IntegerField(choices=[(-1, 'Wants_less_of_same_content'), (0, 'Indifferent_to_post'), (1, 'Wants_more_of_same_content')], default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_by', to='post_profile.postprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched', to='user_profile.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='postprofile',
            name='watchedBy',
            field=models.ManyToManyField(through='post_profile.Watched', to='user_profile.UserProfile'),
        ),
    ]
