# Generated by Django 3.1.5 on 2021-03-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_profile', '0003_postprofile_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='postprofile',
            name='image',
            field=models.BooleanField(default=False),
        ),
    ]
