# Generated by Django 3.1.5 on 2021-03-02 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_profile', '0004_postprofile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postprofile',
            old_name='image',
            new_name='isImage',
        ),
        migrations.RenameField(
            model_name='postprofile',
            old_name='video',
            new_name='isVideo',
        ),
    ]
