# Generated by Django 3.1 on 2020-12-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male', models.IntegerField(default=10)),
                ('female', models.IntegerField(default=10)),
                ('other', models.IntegerField(default=10)),
                ('y0_12', models.IntegerField(default=10)),
                ('y13_17', models.IntegerField(default=10)),
                ('y18_21', models.IntegerField(default=10)),
                ('y22_25', models.IntegerField(default=10)),
                ('y26_30', models.IntegerField(default=10)),
                ('y31_35', models.IntegerField(default=10)),
                ('y36_45', models.IntegerField(default=10)),
                ('y46_55', models.IntegerField(default=10)),
                ('y56_65', models.IntegerField(default=10)),
                ('y65plus', models.IntegerField(default=10)),
                ('dance', models.IntegerField(default=10)),
                ('comedy', models.IntegerField(default=10)),
                ('trends', models.IntegerField(default=10)),
                ('singing', models.IntegerField(default=10)),
            ],
        ),
    ]
