# Generated by Django 3.0.2 on 2020-12-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male', models.FloatField(default=0.1)),
                ('female', models.FloatField(default=0.1)),
                ('other', models.FloatField(default=0.1)),
                ('y0_12', models.FloatField(default=0.1)),
                ('y13_17', models.FloatField(default=0.1)),
                ('y18_21', models.FloatField(default=0.1)),
                ('y22_25', models.FloatField(default=0.1)),
                ('y26_30', models.FloatField(default=0.1)),
                ('y31_35', models.FloatField(default=0.1)),
                ('y36_45', models.FloatField(default=0.1)),
                ('y46_55', models.FloatField(default=0.1)),
                ('y56_65', models.FloatField(default=0.1)),
                ('y65plus', models.FloatField(default=0.1)),
                ('dance', models.FloatField(default=0.1)),
                ('comedy', models.FloatField(default=0.1)),
                ('trends', models.FloatField(default=0.1)),
                ('singing', models.FloatField(default=0.1)),
            ],
        ),
    ]
