# Generated by Django 3.1.5 on 2021-01-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male', models.FloatField(default=0.1)),
                ('female', models.FloatField(default=0.1)),
                ('other', models.FloatField(default=0.1)),
                ('y0_12', models.FloatField(default=0.1)),
                ('y13_18', models.FloatField(default=0.1)),
                ('y19_24', models.FloatField(default=0.1)),
                ('y25_29', models.FloatField(default=0.1)),
                ('y30_34', models.FloatField(default=0.1)),
                ('y35_39', models.FloatField(default=0.1)),
                ('y40_49', models.FloatField(default=0.1)),
                ('y50_59', models.FloatField(default=0.1)),
                ('y60_up', models.FloatField(default=0.1)),
                ('sports', models.FloatField(default=0.1)),
                ('dance', models.FloatField(default=0.1)),
                ('comedy', models.FloatField(default=0.1)),
                ('skits', models.FloatField(default=0.1)),
                ('lifestyle', models.FloatField(default=0.1)),
                ('art', models.FloatField(default=0.1)),
                ('selfhelp', models.FloatField(default=0.1)),
            ],
        ),
    ]
