# Generated by Django 3.0.2 on 2020-12-09 21:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demographics', '__first__'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProfile',
            fields=[
                ('videoID', models.AutoField(primary_key=True, serialize=False)),
                ('private', models.BooleanField(default=False)),
                ('timeCreated', models.DateTimeField(default=datetime.datetime.now)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created', to='user_profile.UserProfile')),
                ('demographics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demographics.Demographics')),
                ('watchedBy', models.ManyToManyField(related_name='watched', to='user_profile.UserProfile')),
            ],
        ),
    ]
