# Generated by Django 3.1.4 on 2020-12-08 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
        ('demographics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='user_profile.userprofile')),
                ('demographics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demographics.demographics')),
                ('watchedBy', models.ManyToManyField(related_name='watched_by', to='user_profile.UserProfile')),
            ],
        ),
    ]
