# Generated by Django 3.1.4 on 2020-12-09 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20201209_0248'),
        ('video_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoprofile',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created', to='user_profile.userprofile'),
        ),
        migrations.AlterField(
            model_name='videoprofile',
            name='watchedBy',
            field=models.ManyToManyField(related_name='watched', to='user_profile.UserProfile'),
        ),
    ]
