# Generated by Django 3.1.4 on 2020-12-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_profile', '0002_auto_20201209_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
