# Generated by Django 3.1.4 on 2020-12-09 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_profile', '0003_auto_20201209_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoprofile',
            old_name='id',
            new_name='videoID',
        ),
    ]
